version: '2'
services:
  businessproc:
    image: dorissschoi/businessproc
    hostname: businessproc
    container_name: businessproc    
    ports:
      - 8006:1337
      - 8007:8080
    volumes:
      - ${COMPOSEROOT}/businessproc/config/env/development.coffee:/usr/src/app/config/env/development.coffee
      - ${COMPOSEROOT}/businessproc/www/js/config/development.coffee:/usr/src/app/www/js/config/development.coffee
      - /etc/ssl/certs/mobile.ogcio.hksarg.pem:/etc/ssl/certs/mobile.ogcio.hksarg.pem
      - /usr/local/share/ca-certificates/mobile.ogcio.hksarg.crt:/usr/local/share/ca-certificates/mobile.ogcio.hksarg.crt
      #- ${COMPOSEROOT}/businessproc/entrypoint.sh:/usr/src/app/entrypoint.sh
      #- ${COMPOSEROOT}/businessproc:/usr/src/app
      
    env_file:
      - ./.env
    external_links:
      - businessproc_mongo
    networks:
      - activiti_default
      - businessprocmongo_default
    #entrypoint: top -b -d 1000          

networks:
  activiti_default:
    external: true
  businessprocmongo_default:
    external: true