version: '2'
services:
  bprocApp_mongo:
    image: mongo
    container_name: bprocApp_mongo
    hostname: bprocApp_mongo
    ports:
      - 27017
    volumes:
      - ${COMPOSEROOT}/data/bproc_mongodata:/data/db
    command: mongod --directoryperdb
    env_file:
      - ./.env 
    
  bprocApp:
    depends_on:
      - bprocApp_mongo
    image: dorissschoi/businessprocessapp
    container_name: bprocApp
    hostname: bprocApp
    entrypoint: top -b -d 1000
    ports:
      - 8006:1337
      - 8007:8080
    volumes:
      - ${COMPOSEROOT}/businessProcessApp-82/config/env/development.coffee:/usr/src/app/config/env/development.coffee
      - ${COMPOSEROOT}/businessProcessApp-82/www/js/config/development.coffee:/usr/src/app/www/js/config/development.coffee
      - /etc/ssl/certs/mobile.ogcio.hksarg.pem:/etc/ssl/certs/mobile.ogcio.hksarg.pem
      - /usr/local/share/ca-certificates/mobile.ogcio.hksarg.crt:/usr/local/share/ca-certificates/mobile.ogcio.hksarg.crt
      - ${COMPOSEROOT}/businessProcessApp-82/entrypoint.sh:/usr/src/app/entrypoint.sh
      - ${COMPOSEROOT}/businessProcessApp-82:/usr/src/app
    env_file:
      - ./.env 
        
